### ISSUE TITLE
[Must Have] - Fix compilation errors in master

### ISSUE THREAD

**Issue by AlphaPromethium** [SuperV1234/SSVOpenHexagon#232]
Top priority card.

![image](https://user-images.githubusercontent.com/25865659/87904048-0d921400-ca90-11ea-86e9-38fc6bd0ef0b.png)
_As well as some other errors on Info Teddy/Misa's end._

According to him, _"`git bisect` says that 94a6854a12201257a279925f271102c9d6315eff was the commit that introduced the compiler error"_.

**Comment by AlphaPromethium** [comment]
@SuperV1234 feel free to assign the card to yourself if ya can fix this rn, as ya have write access to master.

**Comment by SuperV1234** [comment]
Master is fine. You just need to run `cmake` again.
